name: ttu_mate
description: TTU Mate — attachment letters, cover letters, and CV generator.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_inappwebview: ^6.0.0
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  open_filex: ^4.4.0
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.14

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
